spring.application.name=rule-engine-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/ins_travelinsurance
spring.datasource.username=${DB_RULE_USER:ins_rule_svc}
spring.datasource.password=${DB_RULE_PASSWORD:changeme}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=ins_rule
spring.jpa.open-in-view=false
spring.flyway.enabled=false

app.jwt.secret=${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IHRoYXQgbXVzdCBiZSBhdCBsZWFzdCA1MTIgYml0cyBsb25nIGZvciBIUzUxMg==}
app.jwt.access-token-expiry-minutes=15
app.jwt.refresh-token-expiry-days=7
app.jwt.issuer=travel-insurance-platform

management.endpoints.web.exposure.include=health,info
logging.level.com.insurance=INFO
