spring.application.name=api-gateway-service
server.port=8080

app.jwt.secret=${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IHRoYXQgbXVzdCBiZSBhdCBsZWFzdCA1MTIgYml0cyBsb25nIGZvciBIUzUxMg==}
app.jwt.access-token-expiry-minutes=15
app.jwt.refresh-token-expiry-days=7
app.jwt.issuer=travel-insurance-platform

# Route prefix -> downstream service base URL
gateway.routes[/api/v1/auth]=http://localhost:8081
gateway.routes[/api/v1/users]=http://localhost:8081
gateway.routes[/api/v1/plans]=http://localhost:8082
gateway.routes[/api/v1/products]=http://localhost:8082
gateway.routes[/api/v1/addons]=http://localhost:8082
gateway.routes[/api/v1/quotes]=http://localhost:8084
gateway.routes[/api/v1/policies]=http://localhost:8084
gateway.routes[/api/v1/underwriting]=http://localhost:8087
gateway.routes[/api/v1/claims]=http://localhost:8088
gateway.routes[/api/v1/notifications]=http://localhost:8089
gateway.routes[/api/v1/documents]=http://localhost:8090
gateway.routes[/api/v1/audit]=http://localhost:8091
gateway.routes[/api/v1/rules]=http://localhost:8085

management.endpoints.web.exposure.include=health,info
logging.level.com.insurance=INFO
